/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.ssblur.mtp

import Main
import org.gradle.api.Project
import org.gradle.api.Plugin

open class MarkdownToPatchouliExtension {
    var namespace = "minecraft"
    var bookId = "guide"
    var input = "documentation"
    var output = "generated/src/main/resources"
}

class MarkdownToPatchouliPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        val extension = project.extensions.create("mtp", MarkdownToPatchouliExtension::class.java)

        project.tasks.register("convert") { task ->
            task.doLast {
                val processor = Main(
                    extension.namespace,
                    extension.bookId,
                    project.rootDir.resolve(extension.input).absolutePath,
                    project.rootDir.resolve(extension.output).absolutePath
                )

                processor.debug()
                processor.processDir()
                processor.generate()
            }
        }
    }
}
